sequenceDiagram
  participant A
  participant B
  participant C
  participant D
  participant E
  participant F
  participant G
  A->>B: go
  B->>C: go
  C->>D: go
  D->>E: go
  E->>F: go
  F->>G: go
